### ISSUE TITLE
Can you put an MIT license on this repo?

### ISSUE THREAD

**Issue by Leopere** [beevelop/docker-android#13]
I would like to be able to put an MIT license on my usage of your Dockerfile.  Or just say that you don't mind me licensing my version with that license I'll cite this github issue.

**Comment by beevelop** [comment]
@chamunks Unfortunately this image can not be licensed under the MIT license. The contents (Android SDK, libraries, linux packages) are subject to their respective licenses. I can only license the source code of this Dockerfile if need be.

**Comment by chamunks** [comment]
Right but that's what my suggestion was intended for. Technically no LICENSE.md file means you're applying default copyright to the files in the repo.  I didn't see the Android SDK inside the image.

**Comment by beevelop** [comment]
Alright, I'm fine with licensing the Dockerfile sources under the MIT license. I will add a proper LICENSE file with the next version and additional licensing information to the README.

**Comment by beevelop** [comment]
tackled in #28
