### ISSUE TITLE
Build failure due to license not accepted.

### ISSUE THREAD

**Issue by ghost** [beevelop/docker-android#16]
I recently hooked up my bitbucket pipeline with your dockerfile and it works really great. Thank you for the image. Recently I added google play service sdk to my project and suddenly the build appeared to be failing due to the above error. Can you help me fix this?

Here is the bitbucket-pipelines.yml file that I am using to build my project 

``` 
image: beevelop/android:latest
pipelines:
  default:
    - step:
        script:
          - chmod +x gradlew
          - ./gradlew assembleDebug
          - ./gradlew test
```

And here is the error

``` 
Checking the license for package SDK Patch Applier v4 in /opt/android/licenses
Warning: License for package SDK Patch Applier v4 not accepted.
Checking the license for package Google Repository in /opt/android/licenses
Warning: License for package Google Repository not accepted.
Checking the license for package Android Support Repository in /opt/android/licenses
Warning: License for package Android Support Repository not accepted.
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':sdk'.
      > You have not accepted the license agreements of the following SDK components:
        [SDK Patch Applier v4, Android Support Repository, Google Repository].
        Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
        Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
```

**Comment by eiabea** [comment]
Had the same issue, this post helped me resolving it:

[https://stackoverflow.com/a/42138411](https://stackoverflow.com/a/42138411)

**Comment by divanvb** [comment]
Having this issue now as well when using the ionic docker image

**Comment by jurevert** [comment]
It seems that problem do not appear with android-26 sdk (cordova-android 6.3.0).
You can set cordova-android in config.xml by adding:
<engine name="android" spec="6.3.0" />
in config.xml file.

**Comment by beevelop** [comment]
I will do some changes to the next version of this image. This might require you to accept the Android SDK licenses before being able to build you applications. I'll add a proper documentation to simplify that. I'm currently testing those changes in my own CI / CD setup (see the `next` branch and open PR).

**Comment by pedrofurtado** [comment]
@beevelop Looking forward for this new release! :tada:

**Comment by muratcorlu** [comment]
I'm trying to use ionic docker image to build my app but I have this error. What is workaround in this case?

**Comment by jurevert** [comment]
> I'm trying to use ionic docker image to build my app but I have this error. What is workaround in this case?

Which docker image version are you using? We no longer have this issue with version beevelop/ionic:v4.5.0

**Comment by alesrosina** [comment]
Any plans on working on this or is this no longer maintained?

**Comment by beevelop** [comment]
@alesrosina As we switched our pipelines completely, I am not longer using this image on a daily basis. So feedback and PRs are highly appreciated. But I'll try my best to keep this up-to-date.
