### ISSUE TITLE
Build Failure: Could not find com.google.android.gms:play-services-ads:11.0.2.

### ISSUE THREAD

**Issue by OmkarAmberkar** [beevelop/docker-android#17]
classpath 'com.android.tools.build:gradle:3.0.0-alpha5'
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-milestone-1-all.zip

**Comment by beevelop** [comment]
@OmkarAmberkar Did you figure out, why this issue occurred in the first place? There is a `gapis` branch and docker tag (i.e. `beevelop/docker-android:gapis`) which comes prebuilt with some Google APIs. Maybe this resolves your issue. Feel free to reopen / open a new issue for further investigation.
