### ISSUE TITLE
Request for android-27

### ISSUE THREAD

**Issue by david50407** [beevelop/docker-android#22]
Since Android 8.1 Oreo (API 27) was released at 2017/12/5, chould this image include `android-27` API?

**Comment by beevelop** [comment]
As there were quite some changes to the Android CLI and the sdkmanager, I'm still working on the next major release. You can find the related PR here #21. The Image should be available via the `next` tag from Docker Hub.

**Comment by lovato** [comment]
@david50407 if in a rush, try PR #23 . I did a few changes, and it is working with A27. I baked an image from my github account into dockerhub, and it is working with Jenkins like a breeze.

**Comment by lovato** [comment]
@beevelop I took a look at PR #21 and it seems to be also outdated in a few aspects. And shame on me I didn't see it before I opened mine, so no contamination. And they are considerably different.

**Comment by david50407** [comment]
Thank you guys :)
