### ISSUE TITLE
Docker default user

### ISSUE THREAD

**Issue by WuglyakBolgoink** [beevelop/docker-android#32]
Using root user by default is not secure anymore

https://github.com/beevelop/docker-android/blob/0bb46faa302bf6bd7e6843bd602bd651e09553e9/Dockerfile#L30-L31

https://americanexpress.io/do-not-run-dockerized-applications-as-root/

**Comment by beevelop** [comment]
@WuglyakBolgoink Thank you for the suggestion. For all environments that require a more secure execution, you should always use this image as a **base** image. By default this image runs as root to support the most common use cases for CI / CD.
