### ISSUE TITLE
Failed to install the following Android SDK packages as some licences have not been accepted. 

### ISSUE THREAD

**Issue by bonfimjustino7** [beevelop/docker-android#33]
Used with bitbucket pipeline

What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;29.0.2 Android SDK Build-Tools 29.0.2
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
  
  Using Android SDK: /opt/android

**Comment by zommerfelds** [comment]
For now I solved the problem with:
```
RUN yes | sdkmanager --licenses --sdk_root=$ANDROID_SDK_ROOT
```

I don't know if the license agreement should be automated though.

**Comment by beevelop** [comment]
@bonfimjustino7 Thank you for the heads up and the suggestions. Unfortunately, I am not allowed to accept the license for all the users of this image. Therefore accepting the license is (as tedious as it is) required by the end-user of this image. I added the necessary steps (kudos @zommerfelds) to the README for the base image instructions: https://github.com/beevelop/docker-android#or-use-it-as-a-base-image
