### ISSUE TITLE
Missing ANDROID_HOME

### ISSUE THREAD

**Issue by 69pmb** [beevelop/docker-android#34]
Hey !
I was testing your [cordova docker image](https://github.com/vgaidarji/docker-android-cordova), I used the nighty version.
I stumbled on this error message when I tried running `cordova build android`:
> Failed to find 'ANDROID_HOME' environment variable. Try setting it manually.

I think that `ANDROID_HOME` is missing in your android Dockerfile with the same value that `ANDROID_SDK_ROOT`

**Comment by beevelop** [comment]
@69pmb long time, but I tried to add it to the latest release (https://github.com/beevelop/docker-android/blob/latest/Dockerfile#L10). Hope this helps. Feel free to reopen / provide any feedback 🙏
