### ISSUE TITLE
Support API 32

### ISSUE THREAD

**Issue by zommerfelds** [beevelop/docker-android#35]
Hi,

I got API 32 to work by adding the below to my Dockerfile derived from this one:

```
# Seems required for Gradle in Android 32
RUN apt-get update && apt-get install -y openjdk-11-jdk
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64

# Fix tools installation
RUN mv /opt/android/cmdline-tools /opt/android/tools && mkdir /opt/android/cmdline-tools && mv /opt/android/tools /opt/android/cmdline-tools
ENV PATH $PATH:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin
RUN yes | sdkmanager --licenses
```

https://github.com/beevelop/docker-java would probably need to upgrade to Java 11.

Hopefully that helps a bit. :)

**Comment by Sujay-shetty** [comment]
@beevelop / @zommerfelds any update on this issue? as google made mandatory for updating to API level 31 and above for publishing any new app or updates.

Could you please help on this?

**Comment by zommerfelds** [comment]
@Sujay-shetty I ended up working around the issue by creating my own Dockerfile with the instructions I added above.

But it would be great if we could update this image. Or maybe fork the repo if the maintainer can't update it.

**Comment by beevelop** [comment]
Thank you all for the suggestions. I updated the base image (docker-java) to Java 11 and released a new version. Feedback is highly welcome as I don't use this image anymore on a daily basis. I'll add some minor updates for the latest release to even support API level 33. PRs and other suggestions are always welcome ❤️
