### ISSUE TITLE
Please upgrade android build tools

### ISSUE THREAD

**Issue by dmitrikudrenko** [beevelop/docker-android#9]

**Comment by beevelop** [comment]
@dmitrikudrenko Could you indicate the version you intend to use?

**Comment by dmitrikudrenko** [comment]
I'd like to use 25.0.2 build tools

**Comment by beevelop** [comment]
There were a few changes since 24.X and upgrading doesn't seem straightforward anymore. You can track my progress for `Android SDK 25` in the temporary `next` branch / #10. I will keep you updated over here.

**Comment by beevelop** [comment]
@dmitrikudrenko I got a version with the lates build tools running. Would you mind checking it out? The image is available as `beevelop/android:next`

**Comment by dmitrikudrenko** [comment]
Yeah, it works, but still support libraries (https://github.com/beevelop/docker-android/issues/11) are not available. Is it possible to add them?
